/**
 * The 25 fixed levels.
 *
 * These boards are static data: the game never generates or randomises a level
 * at runtime. Each one was specified by hand (palette, tube count, spare tubes,
 * capacity and a target optimal-solution length) and then materialised with
 * scripts/design-levels.ts, which grades candidates using the solver in
 * src/engine/solver.ts. Every board below is verified solvable by the test
 * suite (__tests__/levels.test.ts).
 *
 * Difficulty rises through more colours, more tubes, deeper tubes, fewer spare
 * tubes and longer optimal solutions (6 moves at level 1, 33 at level 25).
 */
import type { LevelDefinition } from '../engine/types';

export const TOTAL_LEVELS = 25;

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: 1,
    name: 'First Drops',
    difficulty: 'tutorial',
    capacity: 4,
    tubes: [
      ['green', 'orange', 'cyan', 'cyan'],
      ['green', 'green', 'orange', 'orange'],
      ['cyan', 'cyan', 'green', 'orange'],
      [],
      [],
    ],
  },
  {
    id: 2,
    name: 'Two Spares',
    difficulty: 'tutorial',
    capacity: 4,
    tubes: [
      ['yellow', 'yellow', 'blue', 'blue'],
      ['red', 'blue', 'yellow', 'red'],
      ['yellow', 'blue', 'red', 'red'],
      [],
      [],
    ],
  },
  {
    id: 3,
    name: 'Finding Order',
    difficulty: 'tutorial',
    capacity: 4,
    tubes: [
      ['cyan', 'yellow', 'yellow', 'purple'],
      ['purple', 'yellow', 'cyan', 'yellow'],
      ['purple', 'cyan', 'purple', 'cyan'],
      [],
      [],
    ],
  },
  {
    id: 4,
    name: 'Four Hues',
    difficulty: 'easy',
    capacity: 4,
    tubes: [
      ['red', 'blue', 'yellow', 'yellow'],
      ['blue', 'red', 'blue', 'green'],
      ['red', 'green', 'green', 'red'],
      ['green', 'yellow', 'yellow', 'blue'],
      [],
      [],
    ],
  },
  {
    id: 5,
    name: 'Steady Hand',
    difficulty: 'easy',
    capacity: 4,
    tubes: [
      ['green', 'cyan', 'orange', 'green'],
      ['green', 'orange', 'purple', 'cyan'],
      ['orange', 'cyan', 'cyan', 'purple'],
      ['purple', 'green', 'purple', 'orange'],
      [],
      [],
    ],
  },
  {
    id: 6,
    name: 'One Spare',
    difficulty: 'easy',
    capacity: 4,
    tubes: [
      ['blue', 'yellow', 'yellow', 'red'],
      ['blue', 'red', 'blue', 'green'],
      ['red', 'red', 'green', 'yellow'],
      ['yellow', 'green', 'blue', 'green'],
      [],
    ],
  },
  {
    id: 7,
    name: 'Five Alive',
    difficulty: 'easy',
    capacity: 4,
    tubes: [
      ['purple', 'red', 'green', 'orange'],
      ['purple', 'purple', 'green', 'orange'],
      ['blue', 'orange', 'red', 'blue'],
      ['green', 'orange', 'green', 'red'],
      ['blue', 'blue', 'purple', 'red'],
      [],
      [],
    ],
  },
  {
    id: 8,
    name: 'Careful Pour',
    difficulty: 'easy',
    capacity: 4,
    tubes: [
      ['pink', 'cyan', 'orange', 'blue'],
      ['orange', 'yellow', 'blue', 'cyan'],
      ['yellow', 'pink', 'cyan', 'orange'],
      ['blue', 'orange', 'cyan', 'pink'],
      ['pink', 'yellow', 'blue', 'yellow'],
      [],
      [],
    ],
  },
  {
    id: 9,
    name: 'Six Shades',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['blue', 'cyan', 'red', 'blue'],
      ['orange', 'orange', 'yellow', 'green'],
      ['cyan', 'orange', 'yellow', 'blue'],
      ['red', 'cyan', 'green', 'red'],
      ['yellow', 'blue', 'green', 'green'],
      ['cyan', 'red', 'orange', 'yellow'],
      [],
      [],
    ],
  },
  {
    id: 10,
    name: 'Narrow Margin',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['yellow', 'blue', 'red', 'purple'],
      ['blue', 'yellow', 'green', 'purple'],
      ['purple', 'yellow', 'red', 'yellow'],
      ['red', 'green', 'purple', 'green'],
      ['red', 'blue', 'blue', 'green'],
      [],
    ],
  },
  {
    id: 11,
    name: 'Rising Tide',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['green', 'purple', 'pink', 'orange'],
      ['orange', 'cyan', 'green', 'pink'],
      ['cyan', 'yellow', 'yellow', 'cyan'],
      ['purple', 'cyan', 'green', 'pink'],
      ['purple', 'yellow', 'purple', 'yellow'],
      ['orange', 'pink', 'orange', 'green'],
      [],
      [],
    ],
  },
  {
    id: 12,
    name: 'Deep Mix',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['orange', 'purple', 'green', 'orange'],
      ['purple', 'blue', 'green', 'blue'],
      ['purple', 'red', 'purple', 'yellow'],
      ['orange', 'green', 'yellow', 'red'],
      ['blue', 'red', 'yellow', 'yellow'],
      ['blue', 'green', 'orange', 'red'],
      [],
      [],
    ],
  },
  {
    id: 13,
    name: 'Seven Streams',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['green', 'yellow', 'yellow', 'cyan'],
      ['red', 'orange', 'green', 'yellow'],
      ['orange', 'purple', 'blue', 'orange'],
      ['yellow', 'blue', 'purple', 'blue'],
      ['cyan', 'green', 'blue', 'red'],
      ['orange', 'red', 'green', 'cyan'],
      ['purple', 'purple', 'cyan', 'red'],
      [],
      [],
    ],
  },
  {
    id: 14,
    name: 'Tangled',
    difficulty: 'medium',
    capacity: 4,
    tubes: [
      ['orange', 'yellow', 'red', 'pink'],
      ['cyan', 'orange', 'pink', 'pink'],
      ['cyan', 'purple', 'red', 'green'],
      ['purple', 'red', 'purple', 'pink'],
      ['green', 'red', 'yellow', 'yellow'],
      ['purple', 'cyan', 'orange', 'cyan'],
      ['green', 'yellow', 'green', 'orange'],
      [],
      [],
    ],
  },
  {
    id: 15,
    name: 'Tight Fit',
    difficulty: 'hard',
    capacity: 4,
    tubes: [
      ['red', 'orange', 'blue', 'orange'],
      ['red', 'green', 'yellow', 'cyan'],
      ['cyan', 'cyan', 'blue', 'green'],
      ['yellow', 'blue', 'yellow', 'red'],
      ['orange', 'green', 'red', 'cyan'],
      ['yellow', 'orange', 'green', 'blue'],
      [],
    ],
  },
  {
    id: 16,
    name: 'Cross Currents',
    difficulty: 'hard',
    capacity: 4,
    tubes: [
      ['green', 'orange', 'orange', 'green'],
      ['yellow', 'orange', 'blue', 'purple'],
      ['cyan', 'yellow', 'cyan', 'pink'],
      ['yellow', 'blue', 'cyan', 'pink'],
      ['blue', 'green', 'purple', 'orange'],
      ['purple', 'green', 'yellow', 'cyan'],
      ['blue', 'pink', 'purple', 'pink'],
      [],
      [],
    ],
  },
  {
    id: 17,
    name: 'Full Spectrum',
    difficulty: 'hard',
    capacity: 4,
    tubes: [
      ['cyan', 'blue', 'purple', 'pink'],
      ['red', 'green', 'cyan', 'purple'],
      ['green', 'green', 'pink', 'red'],
      ['pink', 'orange', 'blue', 'blue'],
      ['cyan', 'pink', 'red', 'yellow'],
      ['yellow', 'red', 'orange', 'orange'],
      ['orange', 'purple', 'yellow', 'purple'],
      ['green', 'blue', 'yellow', 'cyan'],
      [],
      [],
    ],
  },
  {
    id: 18,
    name: 'Undertow',
    difficulty: 'hard',
    capacity: 4,
    tubes: [
      ['orange', 'yellow', 'blue', 'pink'],
      ['red', 'green', 'purple', 'orange'],
      ['yellow', 'green', 'cyan', 'purple'],
      ['cyan', 'purple', 'red', 'pink'],
      ['blue', 'yellow', 'red', 'cyan'],
      ['pink', 'orange', 'green', 'blue'],
      ['blue', 'green', 'cyan', 'orange'],
      ['purple', 'red', 'yellow', 'pink'],
      [],
      [],
    ],
  },
  {
    id: 19,
    name: 'Deep Vessels',
    difficulty: 'hard',
    capacity: 5,
    tubes: [
      ['red', 'orange', 'cyan', 'green', 'pink'],
      ['blue', 'orange', 'pink', 'blue', 'pink'],
      ['blue', 'green', 'pink', 'red', 'red'],
      ['green', 'cyan', 'red', 'cyan', 'red'],
      ['blue', 'cyan', 'pink', 'orange', 'cyan'],
      ['orange', 'blue', 'orange', 'green', 'green'],
      [],
      [],
    ],
  },
  {
    id: 20,
    name: 'Bottleneck',
    difficulty: 'hard',
    capacity: 4,
    tubes: [
      ['red', 'cyan', 'blue', 'cyan'],
      ['purple', 'yellow', 'purple', 'red'],
      ['green', 'red', 'cyan', 'orange'],
      ['yellow', 'orange', 'red', 'green'],
      ['purple', 'cyan', 'purple', 'green'],
      ['orange', 'yellow', 'yellow', 'blue'],
      ['orange', 'green', 'blue', 'blue'],
      [],
    ],
  },
  {
    id: 21,
    name: 'Spectrum Storm',
    difficulty: 'expert',
    capacity: 4,
    tubes: [
      ['blue', 'cyan', 'red', 'yellow'],
      ['green', 'purple', 'orange', 'pink'],
      ['orange', 'yellow', 'purple', 'blue'],
      ['pink', 'cyan', 'pink', 'purple'],
      ['yellow', 'orange', 'green', 'blue'],
      ['yellow', 'red', 'pink', 'orange'],
      ['cyan', 'purple', 'blue', 'red'],
      ['green', 'red', 'green', 'cyan'],
      [],
      [],
    ],
  },
  {
    id: 22,
    name: 'Cascade',
    difficulty: 'expert',
    capacity: 5,
    tubes: [
      ['orange', 'orange', 'blue', 'orange', 'blue'],
      ['red', 'cyan', 'yellow', 'purple', 'orange'],
      ['purple', 'cyan', 'green', 'cyan', 'purple'],
      ['blue', 'yellow', 'purple', 'green', 'red'],
      ['blue', 'yellow', 'purple', 'green', 'yellow'],
      ['orange', 'red', 'green', 'green', 'yellow'],
      ['cyan', 'blue', 'red', 'red', 'cyan'],
      [],
      [],
    ],
  },
  {
    id: 23,
    name: 'Slow Separation',
    difficulty: 'expert',
    capacity: 5,
    tubes: [
      ['blue', 'cyan', 'blue', 'orange', 'cyan'],
      ['orange', 'cyan', 'pink', 'orange', 'pink'],
      ['yellow', 'yellow', 'purple', 'green', 'yellow'],
      ['orange', 'pink', 'blue', 'yellow', 'green'],
      ['yellow', 'pink', 'purple', 'purple', 'orange'],
      ['green', 'cyan', 'green', 'green', 'blue'],
      ['pink', 'cyan', 'purple', 'blue', 'purple'],
      [],
      [],
    ],
  },
  {
    id: 24,
    name: 'Undercurrent',
    difficulty: 'expert',
    capacity: 5,
    tubes: [
      ['orange', 'orange', 'purple', 'blue', 'green'],
      ['red', 'pink', 'cyan', 'blue', 'yellow'],
      ['orange', 'pink', 'orange', 'purple', 'green'],
      ['blue', 'cyan', 'red', 'purple', 'red'],
      ['cyan', 'pink', 'green', 'purple', 'purple'],
      ['cyan', 'orange', 'red', 'pink', 'green'],
      ['yellow', 'yellow', 'yellow', 'blue', 'cyan'],
      ['red', 'yellow', 'pink', 'green', 'blue'],
      [],
      [],
    ],
  },
  {
    id: 25,
    name: 'Final Distillation',
    difficulty: 'expert',
    capacity: 5,
    tubes: [
      ['cyan', 'orange', 'green', 'cyan', 'purple'],
      ['orange', 'green', 'purple', 'cyan', 'orange'],
      ['blue', 'cyan', 'red', 'yellow', 'yellow'],
      ['yellow', 'pink', 'blue', 'green', 'pink'],
      ['cyan', 'red', 'green', 'pink', 'orange'],
      ['purple', 'yellow', 'red', 'green', 'red'],
      ['purple', 'purple', 'yellow', 'orange', 'blue'],
      ['blue', 'pink', 'blue', 'red', 'pink'],
      [],
      [],
    ],
  },
];

/** Looks up a level by its 1-based id. Returns `undefined` for unknown ids. */
export function getLevel(id: number): LevelDefinition | undefined {
  return LEVELS.find((level) => level.id === id);
}

/** True when `id` refers to a level that exists in this build. */
export function isValidLevelId(id: number): boolean {
  return Number.isInteger(id) && id >= 1 && id <= TOTAL_LEVELS;
}

/** The next level after `id`, or `undefined` when `id` is the final level. */
export function getNextLevelId(id: number): number | undefined {
  return id < TOTAL_LEVELS ? id + 1 : undefined;
}
